spring.application.name=smart-campus

# Server Port
server.port=8081

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://root:uc1234@cluster-2.a4ydqil.mongodb.net/
spring.data.mongodb.database=smart_campus_db
