# Server Configuration
server.port=8080

# MongoDB Atlas Connection
# I added 'smart_campus_db' to the end of your URI so the collections are created in the right place
spring.data.mongodb.uri=mongodb+srv://root:uc1234@cluster-2.a4ydqil.mongodb.net/smart_campus_db?retryWrites=true&w=majority

# Logging for Troubleshooting (This will help us if it fails again)
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=DEBUG
