spring.application.name=smart-campus

# Server Port
server.port=8081

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://root:uc1234@cluster-2.a4ydqil.mongodb.net/
spring.data.mongodb.database=smart_campus_db

# Auto-create indexes (needed for @Indexed on email field)
spring.data.mongodb.auto-index-creation=true

# Increase Max Request Size for Images
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB
server.tomcat.max-http-form-post-size=50MB
